# wczytanie danych

In [1]:
import pandas as pd
import numpy as np
import sqlalchemy as sa
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.model_selection import train_test_split
import sklearn.metrics as metrics
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
df_retu1 = pd.read_excel('dane.xlsx')

In [3]:
df_retu = df_retu1.copy()

# zapoznanie się z danymi

## ogólne info o danych

In [4]:
df_retu.head()

,Season,Channel,STCL,ClearanceWeek,RETU,Subclass,SLSU,PriceDiffFromLastRegular,StockCalculationDate,Last2DaysSLSU,Last3DaysSLSU,Last4DaysSLSU,Last5DaysSLSU,BeforeClearanceSeasonSLSU,Last2WeeksBeforeClearanceSLSU,SbclSLSULY,FabricComposition,Line,PredictionsSLSU,RETU_Regular
0,AW 2023,RETAIL,0347N-01X,2,0.0,L_premium,NaN,0.3846,10.0,0,0,0,0,0.0,0.0,105,"93%Silk, 7%Elastane",BLACK LINE,2.0,0.0
1,AW 2023,RETAIL,0347N-01X,3,0.0,L_premium,NaN,0.3846,18.0,0,0,0,0,0.0,0.0,119,"93%Silk, 7%Elastane",BLACK LINE,3.0,0.0
2,AW 2023,RETAIL,0347N-01X,4,-1.0,L_premium,NaN,0.6923,25.0,0,0,0,0,0.0,0.0,268,"93%Silk, 7%Elastane",BLACK LINE,3.0,0.0
3,AW 2023,RETAIL,0347N-01X,5,-1.0,L_premium,NaN,0.7693,26.0,2,4,4,4,0.0,0.0,489,"93%Silk, 7%Elastane",BLACK LINE,3.0,0.0
4,AW 2023,RETAIL,0347N-01X,6,0.0,L_premium,NaN,0.7693,19.0,2,2,2,2,0.0,0.0,1063,"93%Silk, 7%Elastane",BLACK LINE,3.0,0.0

In [5]:
df_retu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 295263 entries, 0 to 295262
Data columns (total 20 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Season                         295263 non-null  object
 1   Channel                        295263 non-null  object
 2   STCL                           295263 non-null  object
 3   ClearanceWeek                  295263 non-null  int64
 4   RETU                           295263 non-null  float64
 5   Subclass                       295263 non-null  object
 6   SLSU                           258471 non-null  float64
 7   PriceDiffFromLastRegular       288720 non-null  float64
 8   StockCalculationDate           282918 non-null  float64
 9   Last2DaysSLSU                  295263 non-null  int64
 10  Last3DaysSLSU                  295263 non-null  int64
 11  Last4DaysSLSU                  295263 non-null  int64
 12  Last5DaysSLSU                  295263 non-null  int64
 13  BeforeClearanceSeasonSLSU      295263 non-null  float64
 14  Last2WeeksBeforeClearanceSLSU  295263 non-null  float64
 15  SbclSLSULY                     295263 non-null  int64
 16  FabricComposition              295218 non-null  object
 17  Line                           295263 non-null  object
 18  PredictionsSLSU                88146 non-null   float64
 19  RETU_Regular                   295263 non-null  float64
dtypes: float64(8), int64(6), object(6)
memory usage: 45.1+ MB

In [6]:
df_retu.shape

(295263, 20)

In [7]:
df_retu.describe()

,ClearanceWeek,RETU,SLSU,PriceDiffFromLastRegular,StockCalculationDate,Last2DaysSLSU,Last3DaysSLSU,Last4DaysSLSU,Last5DaysSLSU,BeforeClearanceSeasonSLSU,Last2WeeksBeforeClearanceSLSU,SbclSLSULY,PredictionsSLSU,RETU_Regular
count,295263.000000,295263.000000,258471.000000,288720.000000,282918.000000,295263.00000,295263.000000,295263.000000,2.952630e+05,295263.000000,295263.000000,295263.000000,88146.000000,295263.000000
mean,6.000000,-10.493872,63.907672,0.465137,269.676465,16.86259,28.102614,39.672197,5.667119e+03,900.445789,108.173069,7985.582769,67.595716,-28.383716
std,2.581993,23.588379,114.108061,0.174952,461.623261,30.92501,50.256286,69.957872,3.131940e+05,1382.947830,217.601792,16566.252595,87.312622,53.730386
min,2.000000,-799.000000,0.000000,-0.498600,1.000000,0.00000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,-1139.000000
25%,4.000000,-11.000000,10.000000,0.363700,27.000000,2.00000,4.000000,6.000000,8.000000e+00,120.000000,8.000000,0.000000,16.000000,-32.000000
50%,6.000000,-2.000000,29.000000,0.500000,104.000000,7.00000,12.000000,18.000000,2.300000e+01,401.000000,35.000000,3025.000000,40.000000,-11.000000
75%,8.000000,0.000000,70.000000,0.600000,318.000000,19.00000,31.000000,44.000000,5.800000e+01,1070.000000,110.000000,8887.000000,84.000000,-3.000000
max,10.000000,0.000000,3504.000000,0.913400,9128.000000,1271.00000,1771.000000,2533.000000,6.930000e+07,18748.000000,5752.000000,130231.000000,1668.000000,0.000000

In [8]:
df_retu.describe(include=['object'])

,Season,Channel,STCL,Subclass,FabricComposition,Line
count,295263,295263,295263,295263,295218,295263
unique,6,3,19084,38,1394,4
top,SS 2022,RETAIL,1920P-80X,JER_t-shirts_s_s,100%Cotton,BLACK LINE
freq,63882,166257,27,33244,51642,146493

In [9]:
df_retu.nunique()

Season                               6
Channel                              3
STCL                             19084
ClearanceWeek                        9
RETU                               412
Subclass                            38
SLSU                              1360
PriceDiffFromLastRegular           389
StockCalculationDate              3859
Last2DaysSLSU                      502
Last3DaysSLSU                      745
Last4DaysSLSU                      952
Last5DaysSLSU                     1246
BeforeClearanceSeasonSLSU         4542
Last2WeeksBeforeClearanceSLSU     1259
SbclSLSULY                        2068
FabricComposition                 1394
Line                                 4
PredictionsSLSU                    778
RETU_Regular                       447
dtype: int64

In [10]:
for col in df_retu.select_dtypes(include=['object']).columns:
    print(f"{col}:\n{df_retu[col].value_counts()}\n")

Season:
Season
SS 2022    63882
SS 2021    52920
SS 2023    51354
AW 2021    48123
AW 2022    42192
AW 2023    36792
Name: count, dtype: int64

Channel:
Channel
RETAIL    166257
ECOM      128906
ECOMMM       100
Name: count, dtype: int64

STCL:
STCL
1920P-80X    27
3019P-55X    27
6804B-59J    18
6823B-05J    18
1394C-01X    18
             ..
1566I-99X     9
1567C-08X     9
1572C-84X     9
1572I-33X     9
9889M-39X     9
Name: count, Length: 19084, dtype: int64

Subclass:
Subclass
JER_t-shirts_s_s         33244
B_dresses                18423
JER_dresses              15669
B_shirts                 14652
B_trousers               14580
W_dresses                14398
W_shirts                 12483
JER_trousers             11637
jeans_trousers           11232
JER_t-shirts_l_s         10944
OUTWEAR_medium           10179
KNIT_blouse               9540
W_trousers                9423
JER_jogging_tops          8739
L_premium                 8424
KNIT_winter               7938
re_capsule                7533
JER_skirts                7038
JER_t-shirts_slvless      7011
OUTWEAR_heavy             6840
KNIT_transitional         6561
B_skirts                  6408
jeans_others              5796
KNIT_cardigan             5463
KNIT_others               5445
B_jackets                 4851
JER_blazers               3798
W_skirts                  3771
W_shorts                  3231
B_shorts                  2592
JER_shorts                2340
W_jackets                 1962
B_outer_jackets            873
KNIT_chunky                747
OUTWEAR_light              738
W_outer_jackets            648
JER______t-shirts_s_s       65
W_dressess                  47
Name: count, dtype: int64

FabricComposition:
FabricComposition
100%Cotton                                      51642
100%Polyester                                   34578
100%Viscose                                     19881
95%Polyester, 5%Elastane                        12726
98%Cotton, 2%Elastane                            7740
                                                ...
79%Modal, 21%Polyester                              9
63%Polyester, 27%Viscose, 8%Wool, 2%Elastane        9
83%Lyocell, 17%Polyamide                            9
60%Viscose, 33%Polyamide, 7%Elastane                9
51%Cotton, 49%Polyester                             9
Name: count, Length: 1394, dtype: int64

Line:
Line
BLACK LINE    146493
WHITE LINE    145674
BASIC           1980
RE.DESIGN       1116
Name: count, dtype: int64

## null

In [11]:
df_retu.isnull().sum()

Season                                0
Channel                               0
STCL                                  0
ClearanceWeek                         0
RETU                                  0
Subclass                              0
SLSU                              36792
PriceDiffFromLastRegular           6543
StockCalculationDate              12345
Last2DaysSLSU                         0
Last3DaysSLSU                         0
Last4DaysSLSU                         0
Last5DaysSLSU                         0
BeforeClearanceSeasonSLSU             0
Last2WeeksBeforeClearanceSLSU         0
SbclSLSULY                            0
FabricComposition                    45
Line                                  0
PredictionsSLSU                  207117
RETU_Regular                          0
dtype: int64

In [15]:
missing_percent = df_retu.isnull().mean() * 100
print(missing_percent)

Season                           0.0
Channel                          0.0
STCL                             0.0
ClearanceWeek                    0.0
RETU                             0.0
Subclass                         0.0
SLSU                             0.0
PriceDiffFromLastRegular         0.0
StockCalculationDate             0.0
Last2DaysSLSU                    0.0
Last3DaysSLSU                    0.0
Last4DaysSLSU                    0.0
Last5DaysSLSU                    0.0
BeforeClearanceSeasonSLSU        0.0
Last2WeeksBeforeClearanceSLSU    0.0
SbclSLSULY                       0.0
FabricComposition                0.0
Line                             0.0
PredictionsSLSU                  0.0
RETU_Regular                     0.0
dtype: float64